baseURL: "https://juftin.com/"
title: juftin
paginate: 5
theme: PaperMod

outputs:
    home:
        - HTML
        - RSS
        - JSON

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    title: juftin
    description: musings from a computer guy
    keywords: [Blog, Portfolio, PaperMod, Hugo, juftin, Python, Software Engineer]
    DateFormat: "January 2, 2006"
    defaultTheme: auto
    disableThemeToggle: false
    hideFooter: true

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        favicon: /static/favicon.ico
        favicon16x16: /static/favicon-16x16.png
        favicon32x32: /static/favicon-32x32.png

    label:
        text: "juftin"
        icon: /static/juftin.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true
        title: what's juftin up to?
        subtitle: |
            and <a href="/about/" style="text-decoration: underline;">who's juftin?</a>
        imageUrl: /static/justin_flannery.png
        imageWidth: 280
        imageHeight: 280
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags
    socialIcons:
        - name: github
          url: https://github.com/juftin
        - name: linkedin
          url: https://linkedin.com/in/justinflannery
        - name: email
          url: mailto:justin.flannery@juftin.com

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/juftin/juftin.github.io/content"
        Text: "Suggest Changes"
        appendFilePath: true
        disabled: true

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: about
          name: about
          url: /about/
          weight: 10
        - identifier: work
          name: work
          url: /work/
          weight: 20
        - identifier: posts
          name: posts
          url: /posts/
          weight: 30
        - identifier: links
          name: links
          url: /links/
          weight: 40
        - identifier: github
          name: github
          url: https://github.com/juftin
          weight: 50
        - identifier: cv
          name: cv
          url: /resume/
          weight: 60

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
    highlight:
        noClasses: false
        anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: false
        style: monokai
    goldmark:
        renderer:
            unsafe: true
